### PR TITLE
Bump the deno-slack-api version

### PR DESCRIPTION
**Pull request by WilliamBergamin**
###  Summary

This PR simply bumps the deno-slack-api version to the latest

### Requirements

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/deno-slack-sdk/blob/main/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

### CODE REVIEW

**Review by filmaj — APPROVED** [review]

**Review by filmaj — CHANGES_REQUESTED** [review]
Wait! Some samples integration tests failed!

**Comment by filmaj** [comment]
@WilliamBergamin when I updated the sample's import of deno-slack-api to the latest version, then this error goes away.

The fact that developers have to import both SDK and API, and the SDK includes an API version in it as well, is troublesome. Easy to get out of sync.

**Comment by WilliamBergamin** [comment]
Ohh I see, when I tried to update deno-slack-api it was still breaking but I was using the old version of the SDK.

Maybe would should not tell devs to import the API independently maybe the SDK should export it and users should use that one by default?

**Comment by WilliamBergamin** [comment]
The [action found](https://github.com/slackapi/deno-slack-api/actions/runs/4887786928) related to the PR that caused this github action to fail are passing.

The reason behind this is that the Github action found in the deno-slack-api repo properly substitutes the deno-slack-api version in the sample project  as well as in the deno-slack-sdk package. The action present in this package only substitutes the deno-slack-sdk version in the sample project without updating the deno-slack-api version

For this reason I will merge this PR and we will address the issue of package desynchronization in the near future

**Pull request merged**
